'use client';

import { useEffect, useMemo } from 'react';
import {
  MapContainer,
  TileLayer,
  Marker,
  Popup,
  useMap,
} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

// --------------------------------------------------
// LEAFLET MARKER ICON
// --------------------------------------------------

const customMarkerIcon = L.icon({
  iconUrl:
    'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',

  iconRetinaUrl:
    'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',

  shadowUrl:
    'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',

  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  shadowSize: [41, 41],
});

// --------------------------------------------------
// ACTIVITY TYPE
// --------------------------------------------------

export interface Activity {
  id: string;
  timeSlot: string;
  title: string;
  description: string;
  locationName: string;

  // Coordinates generated by the LLM
  lat: number;
  lng: number;

  estimatedCostINR: number;
  category: string;

  // Optional fields
  imageUrl?: string;
  duration?: string;
  travelToNext?: string;
}

// --------------------------------------------------
// MAP CONTROLLER
// --------------------------------------------------

function MapController({
  activities,
}: {
  activities: Activity[];
}) {
  const map = useMap();

  const bounds = useMemo(() => {
    if (activities.length === 0) {
      return null;
    }

    const coordinates = activities.map((activity) => [
      Number(activity.lat),
      Number(activity.lng),
    ] as [number, number]);

    return L.latLngBounds(coordinates);
  }, [activities]);

  useEffect(() => {
    // Leaflet can initialize before the parent container
    // has its final dimensions.
    const timer = setTimeout(() => {
      map.invalidateSize();

      if (bounds && bounds.isValid()) {
        map.fitBounds(bounds, {
          padding: [50, 50],
          maxZoom: 14,
        });
      }
    }, 200);

    return () => {
      clearTimeout(timer);
    };
  }, [map, bounds]);

  return null;
}

// --------------------------------------------------
// MAP VIEW
// --------------------------------------------------

export default function MapView({
  activities = [],
}: {
  activities: Activity[];
}) {
  // ------------------------------------------------
  // VALIDATE AI-GENERATED COORDINATES
  // ------------------------------------------------

  const validActivities = useMemo(() => {
    return activities.filter((activity) => {
      const lat = Number(activity.lat);
      const lng = Number(activity.lng);

      return (
        Number.isFinite(lat) &&
        Number.isFinite(lng) &&
        lat >= -90 &&
        lat <= 90 &&
        lng >= -180 &&
        lng <= 180
      );
    });
  }, [activities]);

  // ------------------------------------------------
  // NO ACTIVITIES
  // ------------------------------------------------

  if (!activities || activities.length === 0) {
    return (
      <div className="h-[450px] w-full rounded-2xl border border-slate-200 bg-slate-100 flex flex-col items-center justify-center text-slate-400">
        <div className="text-3xl mb-3">🗺️</div>

        <p className="text-sm font-medium">
          No activities available for this day.
        </p>

        <p className="text-xs mt-1">
          The map will appear when itinerary locations are available.
        </p>
      </div>
    );
  }

  // ------------------------------------------------
  // NO VALID COORDINATES
  // ------------------------------------------------

  if (validActivities.length === 0) {
    return (
      <div className="h-[450px] w-full rounded-2xl border border-slate-200 bg-slate-100 flex flex-col items-center justify-center text-slate-400 px-6 text-center">
        <div className="text-3xl mb-3">📍</div>

        <p className="text-sm font-medium">
          No valid map coordinates available.
        </p>

        <p className="text-xs mt-2 max-w-sm">
          The AI itinerary did not provide usable latitude and
          longitude values for this day's activities.
        </p>
      </div>
    );
  }

  // ------------------------------------------------
  // INITIAL CENTER
  // ------------------------------------------------

  const center: [number, number] = [
    Number(validActivities[0].lat),
    Number(validActivities[0].lng),
  ];

  // ------------------------------------------------
  // UNIQUE MAP KEY
  //
  // Important when switching:
  // Day 1 → Day 2 → Day 3 → Day 4
  //
  // It forces Leaflet to correctly rebuild the map
  // for the newly selected day's locations.
  // ------------------------------------------------

  const mapKey = validActivities
    .map(
      (activity) =>
        `${activity.id}-${activity.lat}-${activity.lng}`
    )
    .join('|');

  // ------------------------------------------------
  // MAP
  // ------------------------------------------------

  return (
    <div
      className="relative w-full overflow-hidden rounded-2xl"
      style={{
        height: '450px',
        minHeight: '450px',
      }}
    >
      <MapContainer
        key={mapKey}
        center={center}
        zoom={13}
        scrollWheelZoom={false}
        className="h-full w-full"
        style={{
          height: '100%',
          width: '100%',
          minHeight: '450px',
          zIndex: 0,
        }}
      >
        {/* ------------------------------------------
            OPENSTREETMAP TILES
        ------------------------------------------ */}

        <TileLayer
          attribution="&copy; OpenStreetMap contributors"
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />

        {/* ------------------------------------------
            AUTOMATICALLY FIT MAP TO ACTIVITIES
        ------------------------------------------ */}

        <MapController
          activities={validActivities}
        />

        {/* ------------------------------------------
            ACTIVITY MARKERS
        ------------------------------------------ */}

        {validActivities.map((activity, index) => (
          <Marker
            key={activity.id || `marker-${index}`}
            position={[
              Number(activity.lat),
              Number(activity.lng),
            ]}
            icon={customMarkerIcon}
          >
            <Popup>
              <div className="min-w-[200px] p-1 font-sans">
                {/* TIME */}

                {activity.timeSlot && (
                  <span className="block text-[10px] uppercase font-bold text-amber-600">
                    {activity.timeSlot}
                  </span>
                )}

                {/* TITLE */}

                <strong className="mt-1 block text-sm font-bold text-slate-800">
                  {activity.title}
                </strong>

                {/* LOCATION */}

                {activity.locationName && (
                  <span className="mt-1 block text-xs text-slate-500">
                    📍 {activity.locationName}
                  </span>
                )}

                {/* DESCRIPTION */}

                {activity.description && (
                  <p className="mt-2 text-xs leading-relaxed text-slate-500">
                    {activity.description}
                  </p>
                )}

                {/* CATEGORY */}

                {activity.category && (
                  <span className="mt-2 inline-block rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">
                    {activity.category}
                  </span>
                )}

                {/* DURATION */}

                {activity.duration && (
                  <span className="ml-1 inline-block rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">
                    ⏱ {activity.duration}
                  </span>
                )}

                {/* COST */}

                {typeof activity.estimatedCostINR ===
                  'number' && (
                  <div className="mt-2 text-xs font-semibold text-emerald-600">
                    ₹
                    {activity.estimatedCostINR.toLocaleString(
                      'en-IN'
                    )}
                  </div>
                )}
              </div>
            </Popup>
          </Marker>
        ))}
      </MapContainer>
    </div>
  );
}